---
abstract: 'A Perl interface to the Unicorn webserver'
author:
  - 'Mugen Kenichi <mugen.kenichi@uninets.eu>'
build_requires:
  Module::Build: 0.38
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicorn-Manager
no_index:
  directory:
    - t
provides:
  Unicorn::Manager:
    file: lib/Unicorn/Manager.pm
    version: 0.006009
  Unicorn::Manager::CLI:
    file: lib/Unicorn/Manager/CLI.pm
    version: 0.006009
  Unicorn::Manager::CLI::Proc:
    file: lib/Unicorn/Manager/CLI/Proc.pm
    version: 0.006009
  Unicorn::Manager::CLI::Proc::Table:
    file: lib/Unicorn/Manager/CLI/Proc.pm
    version: 0
  Unicorn::Manager::Server:
    file: lib/Unicorn/Manager/Server.pm
    version: 0.006009
  Unicorn::Manager::Server::PreFork:
    file: lib/Unicorn/Manager/Server/PreFork.pm
    version: 0
  Unicorn::Manager::Types:
    file: lib/Unicorn/Manager/Types.pm
    version: 0.006009
  Unicorn::Manager::Version:
    file: lib/Unicorn/Manager/Version.pm
    version: 0.006009
requires:
  B::Hooks::OP::Check: 0.19
  Carp: 0
  Cwd: 0
  File::Basename: 0
  Getopt::Long: 0
  IO::Socket: 0
  JSON: 0
  Moo: 0
  Net::Interface: 0
  Net::Server::PreFork: 0
  Proc::Daemon: 0
  Test::More: 0
  Time::HiRes: 0
  YAML: 0
  autodie: 0
  bareword::filehandles: 0
  indirect: 0
  multidimensional: 0
resources:
  license: http://www.opensource.org/licenses/mit-license.php
  repository: https://github.com/mugenken/Unicorn
version: 0.006009
