---
abstract: 'A Perl interface to the Unicorn webserver'
author:
  - 'Mugen Kenichi <mugen.kenichi@uninets.eu>'
build_requires:
  Module::Build: 0.38
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicorn-Manager
no_index:
  directory:
    - t
provides:
  Unicorn::Manager:
    file: lib/Unicorn/Manager.pm
    version: v0.4.1
  Unicorn::Manager::Proc:
    file: lib/Unicorn/Manager/Proc.pm
    version: v0.4.1
  Unicorn::Manager::Types:
    file: lib/Unicorn/Manager/Types.pm
    version: v0.4.1
  Unicorn::Manager::Version:
    file: lib/Unicorn/Manager/Version.pm
    version: v0.4.1
requires:
  Carp: 0
  File::Basename: 0
  Getopt::Long: 0
  JSON: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Declare: 0.34
  Test::More: 0
  YAML: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.04.01
